### ISSUE TITLE
Add the ...custom passthrough to all components.

### ISSUE THREAD

**Issue by matthewtgilbride** [ckshekhar73/react-semantic-redux-form#13]
For instance, I would prefer to use the ToggleField component, so that I get true or false (as opposed to undefined) for the value in my form state.  However, I need to conditionally set that field to readonly, and can't because the props don't get passed down.

I also think this would fix the inline issue: #12

**Comment by ckshekhar** [comment]
Yes, that will fix issue #12 but inline props is included to fix the inline issue.
