### ISSUE TITLE
FormGroup: widths not honored with npm module (works with built index.js)

### ISSUE THREAD

**Issue by matthewtgilbride** [ckshekhar73/react-semantic-redux-form#15]
I am experiencing a strange issue where the width prop of a Field inside a FormGroup is ignored.  This only happens when I import the InputField component from node_modules.  If I clone the repo, build it, and import from dist/index.js, it works fine.

Strange...

Here's some code you can use to demonstrate: https://gist.github.com/mtg5014/3ffe321e24b60cba8e055c91d5dc13f6

Note the difference between the two imports of InputField.

Am I the only one experiencing this?

**Comment by ckshekhar** [comment]
I have tested InputField component, it works just fine. 
Refer to [Demo](https://codesandbox.io/s/2o061l65yp) where I have create WidthExample.jsx with your code and it seems to work as expected. Do let me know if I miss something

**Comment by ckshekhar** [comment]
I am closing for now. Reopen if required.
