### ISSUE TITLE
SelectField with AllowAdditions adds to state but not to element

### ISSUE THREAD

**Issue by notflip** [ckshekhar73/react-semantic-redux-form#18]
I'm using the following code to render a SelectField with allowAdditions.
When I add items I see them being added in the state, but the element itself doesn't show a new tag.

    <Field
                name='tags'
                component={SelectField}
                multiple
                allowAdditions
                label='Tags'
                options={[
                    {key: 'test', value: 'test', text: 'Test'},
                    {key: 'two', value: 'two', text: 'Test 2'},
                ]}/>

Is there something I'm forgetting?
Thank you!

**Comment by ckshekhar** [comment]
You have to handle _**onAddItem**_ event and update component options new value.
Please refer below link for details.
[https://react.semantic-ui.com/modules/dropdown#dropdown-example-allow-additions](https://react.semantic-ui.com/modules/dropdown#dropdown-example-allow-additions)

Feel free to reach me for any clarification.
Thanks

**Comment by notflip** [comment]
Thanks for your reply! I saw that, the only issue is that then the state is being held by the component and not by the global state? As what the plugin is supposed to do?

**Comment by ckshekhar** [comment]
If options are mapped to redux state(global state) then you can update global state by dispatching action based on your app.
This plugin is only meant to use **_semantic-ui-react_** with **_redux-form_**.

**Comment by notflip** [comment]
I'll have to look into that! Unless you have an example somewhere? It's hard with the combination of all libraries to know who does what. :)

**Comment by notflip** [comment]
So in the example you posted, I should just dispatch an action that is in redux-form? instead of writing to the local component state?

**Comment by ckshekhar** [comment]
Your select options is stored in global state or component state?

**Comment by notflip** [comment]
Global state, since I'm using redux-form. Which stores all form values in the global state, right?

**Comment by ckshekhar** [comment]
Yes, you have to update options (which is passed to SelectField in your redux-form) where ever it may be stored either in global store or component store. 

I can say exactly how to update only if i know your app structure. If possible share code with me.

**Comment by notflip** [comment]
**Thanks for your time!** This is the code

So I have the TagSelect component, with the internal state of the tags, passed as you said.
Then the Adapter which passes the props, and it's implemented using field in NoteForm.

    class TagSelect extends Component {
    
        state = {tags: this.props.options};
    
        handleAddition = (e, {value}) => {
            this.setState({
                tags: [{text: value, value}, ...this.state.tags],
            })
        };
    
        render() {
            return (
                <Dropdown
                    onAddItem={this.handleAddition}
                    onChange={this.props.onChange}
                    search
                    selection
                    multiple
                    allowAdditions
                    options={this.state.tags}
                    noResultsMessage='Add a new tag'/>
            );
        }
    }
    
    const TagSelectAdapter = props => {
        return (
            <TagSelect {...props.input} options={props.options} />
        )
    };
    
    
    let NoteForm = props => {
    
        const {handleSubmit} = props;
    
        return (
            <Form onSubmit={handleSubmit}>
    
                <Field
                    required
                    multiple
                    name='tags'
                    component={TagSelectAdapter}
                    options={[{key: 'test', value: 'test', text: 'Test'}]}
                    label='Tags'/>
    
            </Form>
        );
    }

## Internal updating is ok now, but every new select item just overwrites the state in redux, instead of appending to an array..

**Comment by ckshekhar** [comment]
TagSelect and TagSelectAdapter components are not required.
Do something like this.

```javascript
import {DropdownField} from 'react-semantic-redux-form';

let NoteForm = props => {
    
    const {handleSubmit, onAddItem, options} = props;

    return (
        <Form onSubmit={handleSubmit}>

            <Field
                required
                name='tags'
                search
                selection
                multiple
                allowAdditions
                onAddItem={onAddItem}
                component={DropdownField}
                options={options}
                label='Tags'/>

        </Form>
    );
}


// Parent component of NoteForm
handleAddition(e, {value}) {
   // Update options props where ever it is coming from or might be stored in global store.
    //if from global store then dispatch action to update something like below
    dispatch(updateOptions(key: value, value))
   
}
// parent component render
<NoteForm options={this.props.options} onSubmit={this.handleSubmit} 
    onAddItem={this.handleAddition}
```
Do let me know if anything is required.

**Comment by notflip** [comment]
If I 

    console.log(values); // in handleAddition

I get undefined. Am I missing something?
Thank you!

**Comment by ckshekhar** [comment]
Is it working?

**Comment by notflip** [comment]
Im still trying to figure out how to mingle redux-form into thism If i
manually update the state I'm not using redux-store, right? Since that
should be handling the <Field component's state?

**Comment by ckshekhar** [comment]
Is your project on github? If then share the link.

**Comment by notflip** [comment]
I'll upload it asap! Thanks for your time.

**Comment by notflip** [comment]
https://github.com/notflip/Todayilearned

Uploaded! thanks for your time!

**Comment by ckshekhar** [comment]
Your project does not have any component similar to above implementation

**Comment by notflip** [comment]
My goodness I pushed the wrong branch. I pushed the correct one now. So sorry!

    Todayilearned/src/components/
