### ISSUE TITLE
defaultValue not setting initial value for Select/Dropdown

### ISSUE THREAD

**Issue by thysruben** [ckshekhar73/react-semantic-redux-form#19]
I would like a value to be preselected when the form is loaded. [react-semenatic-ui docs](https://react.semantic-ui.com/modules/dropdown) mentions defaultValue to set an initial value. This isn't working though.

**Comment by ckshekhar** [comment]
Form initialization can be done in different ways such as redux-form initialize or [https://redux-form.com/7.3.0/examples/initializefromstate/](https://redux-form.com/7.3.0/examples/initializefromstate/) to set initial value.

**_Example_**

**Using initialize method **
```javascript 
import { initialize } from 'redux-form';

initialize('addEditGoalForm', { field1: 'value1', field2: 'value2' })
```
**While decorating form with reduxForm**
```javascript
export default reduxForm({
  form: 'simple', // a unique identifier for this form
  initialValues: { field1: 'value1', field2: 'value2' } //initialize your form
 })(SimpleForm)

**Comment by thysruben** [comment]
Oh! Thank you for informing me about this! My apologies for the inconvenience I have caused.
