### ISSUE TITLE
Failed to compile by create-react-app

### ISSUE THREAD

**Issue by khaki4** [ckshekhar73/react-semantic-redux-form#2]
I tried to build(yarn build) by create-reate-app cli 

> Failed to compile.
Failed to minify the code from this file: 
  ./node_modules/react-semantic-redux-form/dist/index.js:8 

and failed upper reason what's problem?

**Comment by ckshekhar73** [comment]
Package was not compiled properly for production due to missing es2015 in presets.
Bug fixed in 1.1.6

**Comment by ckshekhar** [comment]
Package was not compiled properly for production due to missing es2015 in presets.
Bug fixed in 1.1.6
