### ISSUE TITLE
Upload new version to npmjs.com

### ISSUE THREAD

**Issue by danielgarciagarcia** [ckshekhar73/react-semantic-redux-form#25]
There are several PRs (#22 and #24) needing approval. @ckshekhar would you mind including those into a new version and upload it to npm?

**Comment by ckshekhar** [comment]
Hi @danielgarciagarcia,
I have merged the PRs and upgraded the packages. It would be great if you help me out testing this. I will try to publish a new version soon. I thought no one is using this package anymore. Thanks for reminding me and please feel free to reach me in the future. Thanks.

**Comment by ckshekhar** [comment]
Published version 1.2.7
