### ISSUE TITLE
Toggle, Checkbox, Radio elements not changing checked status.

### ISSUE THREAD

**Issue by ghost** [ckshekhar73/react-semantic-redux-form#4]
I am trying to make any of these work with using the wrapper structure given in this repo. Redux-form change action is firing but the value is not changing and the state is always equal to the prior ones.

Can I ask for a simple example how you managed to make these work? Tried to debug the issue but checked value seems a problematic.

**Comment by ckshekhar** [comment]
Please refer to Demo link & go through RadioExample.jsx for more details. Let redux-form read and set values of these component. For now I am closing this issue, if this does not solve your problem let me know.

**Comment by valentinfily** [comment]
FYI @ckshekhar73 I think RadioExample.jsx is not in the Demo link anymore.

**Comment by ckshekhar** [comment]
@potioventures  refer this link - https://codesandbox.io/s/50kv0nvprn

**Comment by elitenoire** [comment]
I have a problem with the Radio component . You used the same style of checkbox and toggle for it.
I want to implement choosing between Male and Female for a Gender Field. The onClick method only toggles the checked state to true/false

**Comment by ckshekhar** [comment]
@elitenoire Radio and RadioField will be removed. Use below syntax with redux form.
```
<Form.Field>
        <div className='ui radio'>
          <label>
            <Field
              name="sex"
              component="input"
              type="radio"
              value="male"
            />{' '}
            Male
          </label>
          <label>
            <Field
              name="sex"
              component="input"
              type="radio"
              value="female"
            />{' '}
            Female
          </label>
        </div>
      </Form.Field>

https://codesandbox.io/s/50kv0nvprn

**Comment by snekse** [comment]
Should probably reference this issue in the ReadMe so ppl new to this project understand what/why it states: 

> Radio & RadioField will be removed.
