### ISSUE TITLE
selectOnNavigation is unknown... update semantic-ui-react version

### ISSUE THREAD

**Issue by supersime** [ckshekhar73/react-semantic-redux-form#6]
Have the following:

```JavaScript
                            <Field
                                name="group"
                                component={Select}
                                label="Group"
                                placeholder="Select Group"
                                required
                                options={groupList}
                                selection
                                selectOnBlur={false}
                                selectOnNavigation={false}
                            />

```
However am receiving this error:

> React does not recognize the 'selectOnNavigation' prop on a DOM element.

react-semantic-redux-form is currently using semantic-ui-react 0.71.5 and this issue about selectOnNavigation was resolved in a later version... not sure which one but semantic-ui-react is currently at 0.75.1.

Would it be possible to update the version please?

Thanks!

**Comment by ckshekhar** [comment]
@supersime semantic-ui-react have been update to latest version (0.76.0).
