### ISSUE TITLE
Changing a checkbox doesn't update the store or UI

### ISSUE THREAD

**Issue by supersime** [ckshekhar73/react-semantic-redux-form#7]
Have found an issue where a checkbox isn't updating the store (or on the UI).

I used the [previous sandbox example you gave for checkbox](https://codesandbox.io/s/50kv0nvprn) referenced on this page [Toggle, Checkbox, Radio elements not changing checked status. #4](https://github.com/ckshekhar73/react-semantic-redux-form/issues/4) which works fine with semantic-ui-react version 0.71.5.
If you increase the semantic-ui-react version from 0.71.5 to 0.72.0 it still works, however if you increase to 0.73.0 it no longer works!

Issue appears to have been caused by a change in semantic-ui-react v0.73.0, refer to semantic-ui-react issue [breaking(Checkbox): callback with new checked value in onClick (#2014)](https://github.com/Semantic-Org/Semantic-UI-React/commit/f1f7ceb1dec7f8c45489ca0744b77c4aa3096219) and [breaking(Checkbox): callback with new checked value in onClick by areinmeyer - Pull Request #2014 - Semantic-Org/Semantic-UI-React](https://github.com/Semantic-Org/Semantic-UI-React/pull/2014).
This change to redux-form also appears related: [Checkbox value breaking pristine state - Issue#2857 - erikras/redux-form](https://github.com/erikras/redux-form/issues/2857).

I think the fix might be in the CheckboxField (and Checkbox) functions, where instead of:
`return input.onChange(!data.checked)`

it possibly should be:
`return input.onChange(!!data.checked)`

**Comment by ckshekhar** [comment]
Thanks for pointing out. This issue is resolved in V1.2.1

**Comment by supersime** [comment]
Awesome thanks @ckshekhar73 for such a speedy turnaround!
