### ISSUE TITLE
Select/Dropdown onChange not receiving values

### ISSUE THREAD

**Issue by brianbolnick** [ckshekhar73/react-semantic-redux-form#8]
I may just be doing this wrong, but I am unable to capture a value through onChange inside of either a select or dropdown. Here is an example implementation:

```
<Field
      component={SelectField}
      name='choose'
      label="Choose One"
      options={options}
      onChange={() => (e, { name, value }) => console.log(value);}
      placeholder="Story"
/>
```

I am always getting `undefined` on the change. Do you have a better example of how `onChange` should be implemented, or is this a bug? 

Thanks!

**Comment by ckshekhar** [comment]
@brianbolnick  Use this snippet and refer this https://codesandbox.io/s/2o061l65yp

`<Field
        component={SelectField}
        name='choose'
        label="Choose One"
        options={options}
        onChange={(e, value) => {console.log(value);}}
        placeholder="Choose One"/>`

**Comment by brianbolnick** [comment]
Perfect! Thanks @ckshekhar73 I'll close this out!
